services:
  broker:
    image: eclipse-mosquitto:latest
    container_name: Broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - mqtt-net

  publicador:
    build: ./Publicador
    container_name: Publicador
    environment:
      - MQTT_BROKER=broker
    depends_on:
      - broker
    networks:
      - mqtt-net
    ports:
      - "8000:8000"
    volumes:
      - ./Publicador:/app
      # - ./mosquitto/certs:/certs  # No usar certificados aún

  subscriptor:
    build: ./Suscriptor
    container_name: Subscriptor
    environment:
      - MQTT_BROKER=broker
    depends_on:
      - broker
    networks:
      - mqtt-net
    ports:
      - "8001:8000"
    volumes:
      - ./Suscriptor:/app
      # - ./mosquitto/certs:/certs  # No usar certificados aún

networks:
  mqtt-net: {}