version: "3.8"

services:
  broker:
    image: eclipse-mosquitto:latest
    container_name: Broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - mqtt-net

  capturador:
    build: ./Capturador
    container_name: Capturador
    environment:
      - MQTT_BROKER=broker
    depends_on:
      - broker
    networks:
      - mqtt-net
    ports:
      - "8000:8000"
    volumes:
      - ./Capturador:/app
      # - ./mosquitto/certs:/certs  # No usar certificados aún

  procesador:
    build: ./Procesador
    container_name: Procesador
    environment:
      - MQTT_BROKER=broker
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=calidad_aire
    depends_on:
      - broker
      - db
    networks:
      - mqtt-net
    ports:
      - "8001:8000"
    volumes:
      - ./Procesador:/app
      # - ./mosquitto/certs:/certs  # No usar certificados aún

  db:
    image: postgres:15
    container_name: Postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calidad_aire
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mqtt-net

  grafana:
    image: grafana/grafana:11.6.0
    container_name: Grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - db
    networks:
      - mqtt-net

networks:
  mqtt-net: {}

volumes:
  pgdata:
  grafana_data: