{
 "title": "Proyecto_final",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TOP 10 NO2",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT pais, MAX(valor_dioxido_nitrogeno) as max_valor_dioxido_nitrogeno\r\nFROM calidad_aire \r\nGROUP BY pais \r\nORDER BY MAX(valor_dioxido_nitrogeno) DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "TOP 10 Ozono",
   "type": "barchart",
   "description": "En esta gráfica se encuentran los 20 países con mayor cantidad en valor máximo de ozono detectado",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT pais, MAX(valor_ozono) as max_valor_ozono \r\nFROM calidad_aire \r\nGROUP BY pais \r\nORDER BY MAX(valor_ozono) DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "TOP 10 Particulas finas",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT pais, MAX(valor_particulas_finas) as max_valor_particulas_finas\r\nFROM calidad_aire \r\nGROUP BY pais \r\nORDER BY MAX(valor_particulas_finas) DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Ozono MAP",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    pais as \"Country\",\r\n    AVG (valor_ozono) as \"Ozono Máximo\"\r\nFROM calidad_aire \r\nGROUP BY pais"
    }
   ]
  }
 ]
}